extends Node
const _0_1_TUTORIAL_SEQUENCE = preload("res://scenes/levels/game_sequence/0-1_Tutorial-Sequence.tscn")
const _1_1_TUTORIAL_THROW = preload("res://scenes/levels/game_sequence/1-1_Tutorial_throw.tscn")
const _1_2_DOORS_AND_BUTTONS = preload("res://scenes/levels/game_sequence/1-2 Doors and buttons.tscn")
const _1_3_SCALE_BUTTON = preload("res://scenes/levels/game_sequence/1-3 Scale button.tscn")
const _2_1_CHASE = preload("res://scenes/levels/game_sequence/2-1_CHASE.tscn")
const _2_1_CHASE_CHANGE = preload("res://scenes/levels/game_sequence/2-1_CHASEChange.tscn")
const _3_1_SCALE_LEVEL = preload("res://scenes/levels/game_sequence/3-1 Scale level.tscn")
const _3_2_AROUND_AND_AROUND = preload("res://scenes/levels/game_sequence/3-2 Around and around.tscn")
const _3_3_ONE_STEP_AT_A_TIME = preload("res://scenes/levels/game_sequence/3-3 One step at a time.tscn")
const _4_1_MEATBOKKUSU = preload("res://scenes/levels/game_sequence/4-1 Meatbokkusu.tscn")
const _5_1_RAT_TESTING = preload("res://scenes/levels/game_sequence/5-1 Rat Testing.tscn")
const _6_BOSS = preload("res://scenes/levels/game_sequence/6 Boss.tscn")
const SANDBOX = preload("res://scenes/levels/game_sequence/SANDBOX.tscn")
const J_ELL_YO_UTRO = preload("res://scenes/cutscenes/JellyDOG/jELLYoUTRO.tscn")
const JELLY_INTRO = preload("res://scenes/cutscenes/JellyDOG/JellyIntro.tscn")
const INTRO_CINEMATIC = preload("res://scenes/levels/TitleScreen/intro_cinematic.tscn")
const LEVEL_SELECT = preload("res://scenes/levels/Level_Select/Level_select.tscn")
