extends Node

var _1_1 = "res://scenes/levels/game_sequence/1-1_Tutorial_throw.tscn"
var _1_2 = "res://scenes/levels/game_sequence/1-2 Doors and buttons.tscn"
var _1_3 = "res://scenes/levels/game_sequence/1-3 Scale button.tscn"
var _2_1 = "res://scenes/levels/game_sequence/2-1_CHASE.tscn"
var _2_1_C= "res://scenes/levels/game_sequence/2-1_CHASEChange.tscn"
var _3_1 = "res://scenes/levels/game_sequence/3-1 Scale level.tscn"
var _3_2 = "res://scenes/levels/game_sequence/3-2 Around and around.tscn"
var _3_3  = "res://scenes/levels/game_sequence/3-3 One step at a time.tscn"
var _4_1  = "res://scenes/levels/game_sequence/4-1 Meatbokkusu.tscn"
var _4_2  = "res://scenes/levels/game_sequence/4-2 Templatedante3.tscn"
var _5_1  = "res://scenes/levels/game_sequence/5-1 Rat Testing.tscn"

var WALL_BROKEN = "res://scenes/objects/Wall_Breakable/Wall_Broken.tres"
var J_ELL_YO_UTRO = "res://scenes/cutscenes/JellyDOG/jELLYoUTRO.tscn"
var JELLY_INTRO = "res://scenes/cutscenes/JellyDOG/JellyIntro.tscn"
var INTRO_CINEMATIC = "res://scenes/levels/TitleScreen/intro_cinematic.tscn"
var LEVEL_SELECT = "res://scenes/levels/Level_Select/Level_select.tscn"
var INTRO_CUT = "res://scenes/cutscenes/IntroAnims/IntroCutImproved.tscn"
var BUTTON_RED_PART = "res://scenes/shaders/button_red-part.tres"
var GLASS = "res://scenes/objects/Shaders/Glass.tres"
var SCALE_BUTTON_GREEN_PART = "res://scenes/shaders/scale_button_green-part.tres"
